### ISSUE TITLE
Wrong runner class is generated for non unique set of feature names

### ISSUE THREAD

**Issue by erykator** [trivago/cucable-plugin#192]
**Describe the bug**
Plugin wrongly generates runner class file containing two java classes inside class file. It happens when there are multiple feature files with same name but in different folders.

**To Reproduce**
1. Create SampleFeature.feature in src/feature1 dir
2. Create SampleFeature.feature in src/feature2 dir
3. Set desiredNumberOffFeaturesPerRunner = 1
4. Set parallelizationMode = feature
5. Run Cucable
6. Runner_SampleFeature_feature001_run_001.java file created containing definition of two SampleFeature classes
**Expected behavior**
Two separate files created with unique name, eg:
Runner_SampleFeature1 _feature001_run_001.java running  SampleFeature.feature from src/feature1 dir
Runner_SampleFeature2 _feature001_run_001.java running  SampleFeature.feature from src/feature2 dir

**Comment by bischoffdev** [comment]
Will check this

**Comment by bischoffdev** [comment]
Yes, this is a legitimate bug.

**Comment by bischoffdev** [comment]
Fixed in upcoming `1.14.0`

**Comment by erykator** [comment]
Still does not work, tested in 1.14.0
Still I can see SampleFeature_feature001_run001_IT.feature containing body of both source feature files src/feature1/SampleFeature.feature and src/feature2/**nestedDir**/SampleFeature.feature

Was it fixed in 
parallelizationMode = feature 
?
And was it fixed if feature files are in more  nested directories (see above)?

**Comment by bischoffdev** [comment]
I will open a follow-up one. It was fixed for `parallelizationMode = scenario` only, I'm afraid.

**Comment by bischoffdev** [comment]
Ready to release in 1.14.1
